#!/usr/bin/env bash
#
# Load the environment to work with drush and drupal containers
# Do not run this script but source it like ". load-env"

# No set-e because it's a sourced file

pushd "$(pwd)" > /dev/null

if [ ! -f "./lib/functions" ]; then
    echo "[ERROR] Source this file only from Drucker folder."
    return
fi

cd "./lib"

source functions

if [ -e "../docker-runtime/console/console.rc" ]; then
    source ../docker-runtime/console/console.rc 2>/dev/null
fi

if [ -f "../docker-runtime/drush/drush.bashrc" ]; then
    source ../docker-runtime/drush/drush.bashrc 2>/dev/null
fi

# Include Drush completion.
if [ -f "../docker-runtime/drush/drush.complete.sh" ]; then
    source ../docker-runtime/drush/drush.complete.sh 2>/dev/null
fi

## Include Drush prompt customizations.
#if [ -f "../docker-runtime/drush/drush.prompt.sh" ]; then
#    source ../docker-runtime/drush/drush.prompt.sh
#fi

if [ "${GREETING}"="1" ]; then
    fhelp
fi

popd > /dev/null
