#!/bin/bash

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

messages=()

check_run() {
  echo "$changed_files" | grep -E --quiet "$1" && messages+=("$2")
}

# `npm install` and `npm prune` if the `package.json` file gets changed
check_run "package.json" "> package.json changed! Please run: \e[1mnpm install && npm prune\e[0m"

# `bower install` and `bower prune` if the `bower.json` file gets changed
check_run "bower.json" "> bower.json changed! Please run: \e[1mbower install && bower prune\e[0m"

# `composer install` if the `composer.json` file gets changed
check_run "composer.json" "> composer.json changed! Please run: \e[1mcomposer install\e[0m"

# `gulp css` if new/deleted/updated sass files
check_run ".scss|.sass" "> sass files changed! Please run SASS compilation in the theme(s) folder(s)"

# `drush cim` if config files changed
check_run ".yml" "> yml files changed! Please run: \e[1mdrush cim\e[0m"

# Display messages
if [ ! ${#messages[@]} -eq 0 ]; then
    echo -e "\033[0;34m[DRUCKER] post-merge hook\033[0m"
    for message in "${messages[@]}"
    do
        echo -e "${message}"
    done
fi
