#!/bin/bash

# @TODO: later!
# Because we need to find a proper way to "cd" into the drucker dir
exit

prevHEAD=$1
newHEAD=$2
checkoutType=$3

# Check if it's a checkout of a branch
if [ "${checkoutType}" != "branch" ] || [ "${prevHEAD}" == "${newHEAD}" ]; then
    exit;
fi

echo -e "\033[0;34m[DRUCKER] post-checkout hook\033[0m"

prevBranch=`git name-rev --name-only $prevHEAD`
newBranch=`git name-rev --name-only $newHEAD`

# load functions and environment variables
. functions

# Check if we are on the drucker env
if [ -z "$(type -t "drush")" ]; then
    echo -e "\033[0;31m/!\\ ERROR: The Drucker stack is not running or you're not into the right environment.\033[0m"
    echo "You must execute this script manually before doing anything, otherwise it'll cause side effects!"
    echo "  - start the Drucker stack (drucker start)"
    echo "  - run: ./sql-backup-restore.sh --backup=\"${prevBranch}\" --restore=\"${newBranch}\""
    exit 1;
fi

./sql-backup-restore.sh --backup="${prevBranch}" --restore="${newBranch}"
