#!/usr/bin/env bash
#
# Environment file to start/create named docker containers.
# Source it only in "functions" file.

# No set-e because it's a sourced file

# Load Drucker config
. "../../drucker.config" > /dev/null

domain=${PROJECT_NAME}.local
unset SUBDOMAINS

# owner/group
export DOCKER_USER=`id -u`
export DOCKER_USER_GROUP=`id -g`

# service: php
service=php
export PHP_SERVICE="${service}"
# the container name:
export PHP_NAME="${PROJECT_NAME_PLAIN}_${service}"
# the image to build the container from:
export PHP_IMAGE="ovh/drupal-php:${PHP_VERSION}"
export PHP_IMAGE_CONTEXT="./docker-images/drupal-php/${PHP_VERSION}"
SUBDOMAINS+="${service} "

# service: www
service=www
export WWW_SERVICE="${service}"
# the container name:
export WWW_NAME="${PROJECT_NAME_PLAIN}_${service}"
# the image to build the container from:
export WWW_IMAGE="ovh/drupal-nginx:${DRUPAL_VERSION}-1.13"
export WWW_IMAGE_CONTEXT="./docker-images/drupal-nginx/${DRUPAL_VERSION}/1.13"
SUBDOMAINS+="${service} "

# service: db
service=db
export DB_SERVICE="${service}"
# the container name:
export DB_NAME="${PROJECT_NAME_PLAIN}_${service}"
# the image to build the container from:
export DB_IMAGE="wodby/drupal-mariadb"
# the db root password:
export DB_ROOT_PASSWORD="drootpal"
# credentials for the Drupal database:
export DB_DRUPAL_USER="drupal"
export DB_DRUPAL_DB="drupal"
export DB_DRUPAL_PASSWORD="drupal"
SUBDOMAINS+="${service} "

# service: mail
service=mail
export MAIL_SERVICE="${service}"
# the container name:
export MAIL_NAME="${PROJECT_NAME_PLAIN}_${service}"
# the image to build the container from
export MAIL_IMAGE="mailhog/mailhog"
export MAIL_BIND_PORT=8025
SUBDOMAINS+="${service} "

# service: pma
service=pma
export PMA_SERVICE="${service}"
# the container name:
export PMA_NAME="${PROJECT_NAME_PLAIN}_${service}"
# the image to build the container from
export PMA_IMAGE="phpmyadmin/phpmyadmin"
SUBDOMAINS+="${service} "

export NET_SUBNET="${SUBNET}.0/24"
export NET_GATEWAY="${SUBNET}.1"
i=100 # first IP address (fourth octett)
typeset -u prefix_u
typeset -l prefix_l
for prefix_u in $SUBDOMAINS; do
    prefix_l="${prefix_u}"
    export ${prefix_u}_IP="${SUBNET}.$i"
    export ${prefix_u}_DOMAIN="${prefix_l}.${domain}"
    (( i++ ))
done

# Echo the values set above to create an environment file for use by Docker:
unset PWD SHLVL
env

# -----------------------------------------------------------

# The services/subdomains list
export SUBDOMAINS="$SUBDOMAINS"

# some Docker variables
export DOCKER_ENV="${DRUCKER_DIR}/lib/.docker.env"
export COMPOSE_OPTIONS="--env-file=${DOCKER_ENV}"
export DOCKER_PROJECT_NAME="${PROJECT_NAME_PLAIN}"

# UserId of user www-data in containers
export WWW_USER=${DOCKER_USER}
export WWW_WORKDIR="web"

# set some variables
export net="${PROJECT_NAME_PLAIN}_dev_net"

# Custom images
export NODE_IMAGE="drupal-node:${NODE_VERSION}"
export NODE_CONTEXT="${DRUCKER_DIR}/lib/docker-images/drupal-node/${NODE_VERSION}"

# Wether to show the greeting (1) or not (other value) when opening a terminal
# in PhpStorm
export GREETING=1

# Site install defaults
# ----------------------
# site information
export SITE_NAME="${PROJECT_NAME}"
export ADMIN_USER=admin
export ADMIN_PASSWORD=admin
